CRITICAL - 2021-02-22 00:23:10 --> syntax error, unexpected '[', expecting variable (T_VARIABLE)
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Pers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Pers...')
#3 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(37): spl_autoload_call('App\\Models\\Pers...')
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save()
#5 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2021-02-22 00:35:16 --> syntax error, unexpected 'protected' (T_PROTECTED)
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Pers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Pers...')
#3 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(37): spl_autoload_call('App\\Models\\Pers...')
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save()
#5 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2021-02-22 00:35:53 --> syntax error, unexpected 'protected' (T_PROTECTED)
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Pers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Pers...')
#3 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(37): spl_autoload_call('App\\Models\\Pers...')
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save()
#5 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2021-02-22 00:36:05 --> syntax error, unexpected 'protected' (T_PROTECTED)
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Pers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Pers...')
#3 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(37): spl_autoload_call('App\\Models\\Pers...')
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save()
#5 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2021-02-22 00:36:18 --> syntax error, unexpected 'protected' (T_PROTECTED)
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Pers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Pers...')
#3 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(37): spl_autoload_call('App\\Models\\Pers...')
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save()
#5 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2021-02-22 00:50:44 --> Array to string conversion
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(478): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 478, Array)
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(152): CodeIgniter\Model->first()
#2 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(127): App\Controllers\Personnel->exists('cbms@mail.com', 'CBMS12345')
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->login()
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#5 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2021-02-22 00:53:54 --> Array to string conversion
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(478): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 478, Array)
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(152): CodeIgniter\Model->first()
#2 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(127): App\Controllers\Personnel->exists('cbms@mail.com', 'CBMS12345')
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->login()
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#5 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2021-02-22 00:54:40 --> Array to string conversion
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(478): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 478, Array)
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(152): CodeIgniter\Model->first()
#2 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(127): App\Controllers\Personnel->exists('cbms@mail.com', 'CBMS12345')
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->login()
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#5 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2021-02-22 00:55:28 --> Array to string conversion
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(478): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Array to string...', 'C:\\xampp\\htdocs...', 478, Array)
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(152): CodeIgniter\Model->first()
#2 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(127): App\Controllers\Personnel->exists('test@mail.com', 'test12345')
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->login()
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#5 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2021-02-22 01:09:06 --> Class 'App\Models\Barangay_m' not found
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save()
#1 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2021-02-22 01:31:59 --> Undefined property: App\Controllers\Personnel::$output
#0 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(151): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 151, Array)
#1 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->login()
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-02-22 01:42:24 --> Too few arguments to function App\Controllers\Dashboard::exists(), 0 passed in C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php on line 910 and exactly 2 expected
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Dashboard->exists()
#1 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2021-02-22 01:43:19 --> syntax error, unexpected 'echo' (T_ECHO), expecting ';'
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Router\Router.php(192): CodeIgniter\Router\Router->autoRoute('dashboard/exist...')
#1 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(785): CodeIgniter\Router\Router->handle('dashboard/exist...')
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(358): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-02-22 01:44:08 --> Too few arguments to function App\Controllers\Dashboard::exists(), 1 passed in C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php on line 910 and exactly 2 expected
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Dashboard->exists('12345')
#1 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2021-02-22 01:57:21 --> Undefined property: App\Controllers\Personnel::$output
#0 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(150): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 150, Array)
#1 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->login()
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-02-22 08:06:26 --> There is no data to update.
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(44): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save_questionnaire()
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2021-02-22 08:06:40 --> There is no data to update.
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(44): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save_questionnaire()
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2021-02-22 08:08:48 --> There is no data to update.
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(44): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save_questionnaire()
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2021-02-22 08:11:47 --> There is no data to update.
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(44): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save_questionnaire()
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2021-02-22 08:14:27 --> Undefined variable: data
#0 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(50): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 50, Array)
#1 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save_questionnaire()
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-02-22 08:16:00 --> There is no data to update.
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(50): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save_questionnaire()
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2021-02-22 08:17:51 --> There is no data to update.
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(50): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save_questionnaire()
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2021-02-22 08:18:35 --> There is no data to update.
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(50): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save_questionnaire()
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2021-02-22 08:19:29 --> There is no data to update.
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(48): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save_questionnaire()
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2021-02-22 08:20:18 --> There is no data to update.
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(49): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save_questionnaire()
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2021-02-22 08:33:53 --> There is no data to update.
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(51): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save_questionnaire()
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2021-02-22 08:37:52 --> Unknown column 'id' in 'where clause'
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(330): mysqli->query('UPDATE `bpq_dat...')
#1 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `bpq_dat...')
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Database\BaseConnection.php(666): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `bpq_dat...')
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2410): CodeIgniter\Database\BaseConnection->query('UPDATE `bpq_dat...', Array, false)
#4 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(56): CodeIgniter\Database\BaseBuilder->update(Array)
#5 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save_questionnaire()
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#7 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2021-02-22 08:39:03 --> Unknown column 'id' in 'where clause'
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(330): mysqli->query('UPDATE `bpq_dat...')
#1 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `bpq_dat...')
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Database\BaseConnection.php(666): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `bpq_dat...')
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2410): CodeIgniter\Database\BaseConnection->query('UPDATE `bpq_dat...', Array, false)
#4 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(56): CodeIgniter\Database\BaseBuilder->update(Array)
#5 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save_questionnaire()
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#7 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2021-02-22 08:42:24 --> There is no data to update.
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(48): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save_questionnaire()
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2021-02-22 20:25:47 --> Undefined property: App\Controllers\Personnel::$output
#0 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(171): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 171, Array)
#1 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->login()
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2021-02-22 20:26:19 --> Undefined property: App\Controllers\Personnel::$output
#0 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(171): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 171, Array)
#1 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->login()
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
